name: Create release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment: 'Release'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        name: Set up Java
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Java package
        run: mvn clean package

